// 192.168.1.104
const IP ='http://192.168.1.4:4000';
const ACTION_TYPE_FETCH_COURSES = 'FETCH_COURSES';
const ACTION_TYPE_FETCH_CATGORIES = 'FETCH_CATEGORIES';
const ACTION_TYPE_FETCH_COURSES_LIST = 'FETCH_COURSES_LIST';
const ACTION_TYPE_FETCH_COURSES_ID = 'FETCH_COURSES_ID';

const ACTION_TYPE_FETCH_USER = 'FETCH_USER';

// Chưa dùng
const ACTION_TYPE_FETCH_CATGORIES_SLIDEBAR = 'FETCH_CATEGORIES_SLIDEBAR';

export default {
                IP
                ,ACTION_TYPE_FETCH_COURSES
                ,ACTION_TYPE_FETCH_CATGORIES
                ,ACTION_TYPE_FETCH_CATGORIES_SLIDEBAR
                ,ACTION_TYPE_FETCH_COURSES_LIST
                ,ACTION_TYPE_FETCH_USER
                ,ACTION_TYPE_FETCH_COURSES_ID 
            };